Repository Vivian-RC/controle-gpio-teclado-matricial-rp2040, pull requests merged in 2025-01, with the labels that each got.

#8 Implementação do display lcd 1602
  include/lcd.h
  src/lcd.c
Labels: Revisão necessaria

#10 Adição ao display função atualizar_lcd e limpar_linha
  include/lcd.h
  src/lcd.c
Labels: Revisão necessaria, Aprimoriamento, Recursos

#9 implementação do teclado matricial 4x4
  include/teclado.h
  src/teclado.c
Labels: Revisão necessaria

#11 implementação da inicialização dos componentes
  include/componentes.h
  src/componentes.c
Labels: Revisão necessaria, Testes e depuração

#12 implementação da função de controle dos leds e buzzer
  include/leds_buzzer.h
  src/leds_buzzer.c
Labels: Tarefa em andamento, Revisão necessaria, Testes e depuração

#13 Testes e depuração
  tests/test_componentes.c
  tests/test_lcd.c
  tests/test_leds_buzzer.c
  tests/test_main.c
  tests/test_teclado.c
Labels: Testes e depuração
